# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.10.0] # avoid jest memory issues https://github.com/facebook/jest/issues/11956

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn" # or 'npm' | 'pnpm'

      # Runs a single command using the runners shell
      - name: Switch to Dev
        run: yarn env:switch:dev
      - name: Run install
        run: yarn install
      - name: Run typescript and linter
        run: yarn tsc && yarn lint
      - name: Run formatter
        run: yarn format
      - name: Run update shared-deps
        run: yarn update:shared-deps
      - name: Run tests
        env:
          NODE_OPTIONS: "--max-old-space-size=20480"
        run: yarn test:ci
